### ISSUE TITLE
Can't open page in browser

### ISSUE THREAD

**Issue by JohnCrodian** [mgwismer/NYCDA-SpiceRack#1]
I get the following error in my terminal when I try to initialize the main ruby file, which I believe is keeping me from being able to open it in my browser. 

/Users/johncrodian/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
    from /Users/johncrodian/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from spice-main.rb:1:in `<main>'

**Comment by JohnCrodian** [comment]
Problem solved- hadn't re-installed all of my gems.
